UPDATE losses_adjustments_types SET category = 'RECEIVE' WHERE name IN ('DISTRICT_DDM','PROVINCE_DPM','DEFAULT_RECEIVE');
UPDATE losses_adjustments_types SET category = 'ISSUE' WHERE name IN ('PUB_PHARMACY','MATERNITY','GENERAL_WARD','ACC_EMERGENCY','MOBILE_UNIT','LABORATORY','UATS','PNCTL','PAV','DENTAL_WARD','UNPACK_KIT','DEFAULT_ISSUE');

UPDATE losses_adjustments_types SET category = 'NEGATIVE_ADJUST' WHERE name IN ('EXPIRED_RETURN_TO_SUPPLIER','DAMAGED','LOANS_DEPOSIT','INVENTORY_NEGATIVE','PROD_DEFECTIVE','DEFAULT_NEGATIVE_ADJUSTMENT');

UPDATE losses_adjustments_types SET category = 'POSITIVE_ADJUST' WHERE name IN ('CUSTOMER_RETURN','EXPIRED_RETURN_FROM_CUSTOMER','DONATION','LOANS_RECEIVED','INVENTORY_POSITIVE','RETURN_FROM_QUARANTINE','DEFAULT_POSITIVE_ADJUSTMENT');

UPDATE losses_adjustments_types SET category = 'PHYSICAL_INVENTORY' WHERE name IN ('INVENTORY');
