---
- hosts: prodsim
  connection: ssh
  sudo: yes
  roles:
    - syncdata
    - configuration
    - password
    - one-time-script
    - flyway
    - package
    - cubes
    - db-migration
  vars:
    region: prodsim
