#!/bin/bash
export LC_ALL=C
/home/ubuntu/letsencrypt/letsencrypt-auto renew --force-renew -nvv --webroot > /var/log/letsencrypt/renew.log 2>&1
LE_STATUS=$?
if [ "$LE_STATUS" != 0 ]; then
    echo Automated renewal failed:
    cat /var/log/letsencrypt/renew.log
    exit 1
fi

CERT_NAME="cert-$(date +%H%M%S%d%m%y)"
aws iam upload-server-certificate --server-certificate-name $CERT_NAME --certificate-body file:///etc/letsencrypt/live/lmis1.cuipengfei.me/cert.pem --private-key file:///etc/letsencrypt/live/lmis1.cuipengfei.me/privkey.pem --certificate-chain file:///etc/letsencrypt/live/lmis1.cuipengfei.me/fullchain.pem
aws elb set-load-balancer-listener-ssl-certificate --load-balancer-name test2 --load-balancer-port 443 --ssl-certificate-id arn:aws:iam::745786580020:server-certificate/$CERT_NAME