#!/bin/bash
export LC_ALL=C
/home/ubuntu/letsencrypt/letsencrypt-auto renew --force-renew -nvv --webroot > /var/log/letsencrypt/renew.log 2>&1
LE_STATUS=$?
if [ "$LE_STATUS" != 0 ]; then
    echo Automated renewal failed:
    cat /var/log/letsencrypt/renew.log
    exit 1
fi